### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by rickbergfalk**
Updates dependencies to latest versions. Doing so broke something with the typescript tests. Moving tsconfig.json to root of the project seemed to fix it.

Error message in question was 

```sh
$ npm test

> postgrator@3.6.0 test /Users/rickbergfalk/gitlocal/postgrator
> mocha --require ts-node/register --recursive "test/**/*.{js,ts}"


/Users/rickbergfalk/gitlocal/postgrator/node_modules/ts-node/src/index.ts:261
    return new TSError(diagnosticText, diagnosticCodes)
           ^
TSError: ⨯ Unable to compile TypeScript:
error TS2468: Cannot find global value 'Promise'.
test/api.ts(24,28): error TS2705: An async function or method in ES5/ES3 requires the 'Promise' constructor.  Make sure you have a declaration for the 'Promise' constructor or include 'ES2015' in your `--lib` option.
test/api.ts(34,33): error TS2705: An async function or method in ES5/ES3 requires the 'Promise' constructor.  Make sure you have a declaration for the 'Promise' constructor or include 'ES2015' in your `--lib` option.
test/api.ts(40,39): error TS2705: An async function or method in ES5/ES3 requires the 'Promise' constructor.  Make sure you have a declaration for the 'Promise' constructor or include 'ES2015' in your `--lib` option.
test/api.ts(45,34): error TS2705: An async function or method in ES5/ES3 requires the 'Promise' constructor.  Make sure you have a declaration for the 'Promise' constructor or include 'ES2015' in your `--lib` option.
test/api.ts(55,42): error TS2705: An async function or method in ES5/ES3 requires the 'Promise' constructor.  Make sure you have a declaration for the 'Promise' constructor or include 'ES2015' in your `--lib` option.
test/api.ts(65,34): error TS2705: An async function or method in ES5/ES3 requires the 'Promise' constructor.  Make sure you have a declaration for the 'Promise' constructor or include 'ES2015' in your `--lib` option.
test/api.ts(70,30): error TS2705: An async function or method in ES5/ES3 requires the 'Promise' constructor.  Make sure you have a declaration for the 'Promise' constructor or include 'ES2015' in your `--lib` option.

    at createTSError (/Users/rickbergfalk/gitlocal/postgrator/node_modules/ts-node/src/index.ts:261:12)
    at getOutput (/Users/rickbergfalk/gitlocal/postgrator/node_modules/ts-node/src/index.ts:367:40)
    at Object.compile (/Users/rickbergfalk/gitlocal/postgrator/node_modules/ts-node/src/index.ts:558:11)
    at Module.m._compile (/Users/rickbergfalk/gitlocal/postgrator/node_modules/ts-node/src/index.ts:439:43)
    at Module._extensions..js (module.js:635:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/Users/rickbergfalk/gitlocal/postgrator/node_modules/ts-node/src/index.ts:442:12)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at /Users/rickbergfalk/gitlocal/postgrator/node_modules/mocha/lib/mocha.js:250:27
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (/Users/rickbergfalk/gitlocal/postgrator/node_modules/mocha/lib/mocha.js:247:14)
    at Mocha.run (/Users/rickbergfalk/gitlocal/postgrator/node_modules/mocha/lib/mocha.js:576:10)
    at Object.<anonymous> (/Users/rickbergfalk/gitlocal/postgrator/node_modules/mocha/bin/_mocha:637:18)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Function.Module.runMain (module.js:665:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:607:3
npm ERR! Test failed.  See above for more details.
```

@Codesleuth would you mind taking a look at these updates since I'm not familiar with typescript setups?

### CODE REVIEW

**Comment by Codesleuth** [comment]
@rickbergfalk Apologies for the late response. I'll take a look tomorrow, I'm sure it can be fixed!

**Comment by Codesleuth** [comment]
Using `npm ci` on this branch and running `npm test` I don't get that error. Perhaps your package lock is not updated?

**Comment by Codesleuth** [comment]
@rickbergfalk The change you made makes sense. `ts-node` had a breaking change that means it looks for the `tsconfig.json` in the PWD.

Alternatively you could use [`cross-env`](https://www.npmjs.com/package/cross-env) to change the test script to:

```json
{
  "test": "cross-env TS_NODE_PROJECT=./test/tsconfig.json mocha --require ts-node/register --recursive \"test/**/*.{js,ts}\""
}
```

**Comment by rickbergfalk** [comment]
Thanks for reviewing this @Codesleuth! No worry about a late response or anything. I'm quite delayed on this myself :)

I think I'll leave the tsconfig where it is. Had not heard of cross-env though. looks super useful.

**Pull request merged**
